config/routes.rb
Juralizator::Application.routes.draw do

  root 'search#index'

  get 'get_captcha' => 'search#get_captcha'
  get 'do_search' => 'search#do_search'
  get 'full_search' => 'search#full_search'
  scope :search do
    get 'law' => 'search#law_search'
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
# encoding: utf-8

class SearchController < ApplicationController
  def index
  end
  def get_captcha
    agent = create_agent
    captcha_img_file_path = ""
    agent.get "http://egrul.nalog.ru/" do |page|
      page_new_captcha = agent.get "http://egrul.nalog.ru/?r=new_captcha"
      h_code = JSON.parse page_new_captcha.body
      new_captcha = agent.get "http://egrul.nalog.ru/?r=captcha&h=#{h_code['h']}"
      captcha_img_file_path = "captcha/captcha_#{Digest::SHA1.hexdigest(Time.now.to_s)}.png"
      new_captcha.save  "public/#{captcha_img_file_path}"
    end
      session[:jar] = agent.cookie_jar.jar['egrul.nalog.ru']['/']['PHPSESSID']

    respond_to do |format|
      format.json do
        render json: [captcha: captcha_img_file_path]
      end
    end
  end
  def do_search
    agent = create_agent
    result = nil
    agent.get "http://egrul.nalog.ru/" do |page|
      agent.cookie_jar.jar['egrul.nalog.ru']['/']['PHPSESSID'] = session[:jar]
      puts agent.cookie_jar.jar['egrul.nalog.ru']['/']['PHPSESSID'] 
      result = page.form_with(id: 'search_form') do |form|
        form = page.forms.first
        form.action = "/?r=search"
        form.num = params[:inn]
        form.capcha = params[:captcha]
      end.submit
    end
      respond_to do |format|
        format.json do
          render json: [ result: result.body ]
        end
      end
  end

  def full_search
      result = google_query(create_agent, params[:org][:name].delete("&quot;"))
      result.each do |li|

      end
      first_link_with_site = result.first.search(".r").first.search("a").first.attributes['href'].value
      respond_to do |format|
        format.json do
          render json: [ result: ['site' => first_link_with_site.inspect] ]
        end
      end
  end

  def law_search
    agent = create_agent
    results = agent.get("http://rospravosudie.com/act-#{params[:org][:name].delete("&quot;")}-q/section-acts/").search(".table a")
    results =results.map { |r| [url: r.attributes['href'].value, value: r.text] }
    respond_to do |format|
      format.json do
        render json: [ result: results ]
      end
    end
  end

  private
    def create_agent
      agent = Mechanize.new do |a|
       #a.log = Logger.new('log.txt')
       a.user_agent_alias = "Windows IE 6"
      end
      #unless session[:jar].nil?
      agent
    end
    def create_google_client
      client = Google::APIClient.new
      client.authorization.access_token = 'AIzaSyDQsz0wkqFcJyJ6Qmk6JpUQuhbABmaX4O4'
      search = client.discovered_api('customsearch') 
      return client, search
    end
    def google_query(agent, query)
       agent.get('http://google.com/') do |page|
         result = page.form_with(name: "f") do |form|
           form.field_with(name: 'q').value = query.to_s
         end.submit
         return (result/"li.g")
       end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Juralizator</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top" role="navigation">
   <div class="navbar-header">
    <a class="navbar-brand" href="#">Юранализатор</a>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<div class="container">
        <div class="page-header">
          <h1>Юридическая поисковая система</h1>
        </div>
        <p class="lead">
          <div id="wrap">
          <ul>
            <li>Официальное название компании с наименованием формы собственности</li>
            <li>Дата регистрации</li>
            <li>Дата исключения из ЕГРЮЛ или ликвидации</li>
            <li>Адрес компании</li>
            <li>ФИО директора</li>
            <li>ФИО учредителей</li>
          </ul>
          </div>
          <%= form_tag do_search_path, class:"form-inline", id: "search_form", role: "form" do %>
            <div class="form-group">
              <%= number_field_tag :inn, nil,placeholder: "ИНН", class: "form-control" %>
            </div>
            <div class="form-group" id="captcha_img_div">
               <img src="" id="captcha_img" alt="" />
            </div>
            <div class="form-group" id="captcha_div">
              <%= text_field_tag :captcha, nil,placeholder: "Код",maxlength:4,size:4, class: "form-control" %>
            </div>
            <%= submit_tag "Поиск", class: "btn btn-default" %>
          <% end %>
        </p>
   
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title" id="item-name">Поиск..</h3>
          </div>
          <div class="panel-body" id="info-panel">
            <div>
              <dl>
                <dt>Адрес
                  <dd id="item-address"></dd>
                </dt>
                <dt>Дата включения в базу
                  <dd id="item-date"></dd>
                </dt>
                <dt>Сайт
                  <dd><a id="item-site" href="#"></a></dd>
                </dt>
                <dt>
                  <dd id="item-"></dd>
                </dt>
                <dt>
                  <dd id="item-"></dd>
                </dt>
              </dl>
            </div>
            <div id="inn-list"><h4>ИНН+[номер ИНН]</h4><ul></ul></div>
            <div id="address-list"><h4>адрес_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="mailto-list"><h4>mailto_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="email-list"><h4>email_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="mailru-list"><h4>mail.ru_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="gmail-list"><h4>gmail.com_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="rambler-list"><h4>rambler.ru_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="yandex-list"><h4>yandex.ru_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="credit-list"><h4>долги_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="court-list"><h4>суд_решение_[название компании]_[номер ИНН]</h4><ul></ul></div>
            <div id="more-url">
            <h3>Упоминания в интернете</h3>
              <ul>
                
              </ul>
            </div>
          </div>
        </div>
</div>